### ISSUE TITLE
Completely unusable - slow

### ISSUE THREAD

**Issue by bakman2** [AlUlkesh/stable-diffusion-webui-images-browser#103]
I don't know what this extension is doing in the background, but whenever I click on the image browser tab, it completely bogs down my system, loading a single page takes 3+ minutes - don't even know if it actually finishes what it is doing, as I don't have the patience to wait (Mac M2 Pro) and everything becomes slow on my system. 

Then the images show up, but no data is shown and the image "hover" is trailing my mouse (ie the page is not responding).

**Comment by AlUlkesh** [comment]
Yes, different people have different issues since webui switched to the new Gradio. This includes webui itself and extensions.

What you can try:

- First, make sure you have the latest commits of both webui and this extension
- You can try this: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9055#issuecomment-1485760587
- You can install this PR, while it's waiting to be merged: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9060
- You can try a different browser, Chrome/Firefox

**Comment by bakman2** [comment]
@AlUlkesh not sure why this issue is closed, git pull, same (slow) result ?

**Comment by AlUlkesh** [comment]
I closed this issue, because I got no feedback in 5 days.

Did you try all the things I listed, even if not another browser?
