### ISSUE TITLE
Shortcut keys for 5-star rating are not working.

### ISSUE THREAD

**Issue by Ka-Nako** [AlUlkesh/stable-diffusion-webui-images-browser#108]
I am connecting to Stable Diffusion running on the same network from my Mac. 

While selecting images using arrow keys and pressing number keys to rate them, the ratings are not recorded. 

However, if I click on the image with the mouse and then rate it using the mouse, the rating is recorded. How can I achieve this using only arrow and number keys?

**Comment by AlUlkesh** [comment]
I wonder if this is a database issue. Can you stop webui, rename `wib.sqlite3` to something else and restart webui? A new db will be created then.

If this solves the problem, I'll see about migrating the data from the previous database.

**Comment by Ka-Nako** [comment]
Thank you for your response! 
I'm sorry, but I couldn't find wib.sqlite3 by searching the Stable Diffusion folder. 
Where is it stored?

**Comment by Ka-Nako** [comment]
Thank you. 
After renaming wib.sqlite3 and restarting the WEBUI, the evaluation system with shortcut keys started working!

**Comment by AlUlkesh** [comment]
@Ka-Nako 
Ok, This was a concurrency issue. I had to separate the current value from the value I want to set it to. Otherwise loading a new image would register as trying to change the ranking, before all the image information had been read.

![image](https://user-images.githubusercontent.com/99896447/229159718-5881613d-c478-4a96-a456-9b9996e9f2e5.png)

I suggest you update to the latest commit and rename your original db back to its real name. Otherwise you'll have lost your old rankings.
