### ISSUE TITLE
First/Prev/Next/End Page won't load thumbnail pages

### ISSUE THREAD

**Issue by AlUlkesh** [AlUlkesh/stable-diffusion-webui-images-browser#122]
python: 3.10.10  •  torch: 1.13.1+cu117  •  xformers: 0.0.17.dev464  •  gradio: 3.23.0  •  commit: [22bcc7be]
and df3d5413 images browser

Everything seems to be ok except the First/Prev/Next/End Page won't load thumbnail pages after I click on an image

_Originally posted by @Davey212 in https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/116#issuecomment-1493431686_

**Comment by AlUlkesh** [comment]
@Davey212:
This should fix that issue.

**Comment by badjeff** [comment]
Just found, the query of .preview element is not always returns the element on current tab at [this line](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/blob/4b9755bb946ddcce4b89021271504f032f59f9ec/javascript/image_browser.js#L116).

Steps to trigger an issue:
1. Generated a batch (>1 output) in text2img, click a thumbnail into large preview mode and leave it in preview mode.
2. Goto Images Browser tab, and click first page on any sub-tab, it will show in preview mode first, instead of thumbnails. It will follow the preview state of the element on text2img tab.

After loading a new page, it is forced into preview mode even it was dismissed into thumbnail mode before page jump. It is inconvenient to browse between pages.

**Comment by don1138** [comment]
Same issue.

Current config:
- python: **3.10.10**
- torch: **2.0.0**
- xformers: **N/A**
- gradio: **3.23.0**
- commit: **22bcc7be**

I'm an a M1 Max Macbook, and the versions of SD-UI from the last few weeks have all been incompatible.

I go to the **Image Browser** tab, click on **First**, and the loading icon spins without loading images. (Currently at `664` seconds and counting.

This previous commit of SD-UI is compatible, and has no problems working with **Image Browser**:

- python: **3.10.10**
- torch: **2.0.0**
- xformers: **N/A**
- gradio: **3.16.2**
- commit: **4b159292**

**Comment by AlUlkesh** [comment]
Can you please check if this change solved any of your issues: #126?

**Comment by don1138** [comment]
Just pulled the latest, and same issue.

Only things that comes to mind is that I have almost 5,000 images in the existing folders.

Across the board, browser response in the new SD-UI is a LOT slower and more stuttering than in the previous versions.

**Comment by AlUlkesh** [comment]
I have 17 000 pngs in my biggest folder... So that shouldn't be the issue.

**Comment by AlUlkesh** [comment]
Can you follow the new debug info guide: #130 and post your logs?

**Comment by AlUlkesh** [comment]
Can you all try the latest update please: #135

**Comment by don1138** [comment]
python: **3.10.10**
torch: **2.0.0**
xformers: **N/A**
gradio: **3.23.0**
commit: **22bcc7be**

Pulled the latest version, same issue: click on **First Page** and the loading icon spins forever without loading images.

Enabled **JS Debugging**, restarted, tried again, same.

Console log attached: [Terminal Saved Output.txt](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/files/11194310/Terminal.Saved.Output.txt)

**Comment by AlUlkesh** [comment]
Are you still having this issue?
