### ISSUE TITLE
image browser completely broken for me (Forge & Gradio 4 issue)

### ISSUE THREAD

**Issue by atmogenic** [AlUlkesh/stable-diffusion-webui-images-browser#257]
I stupidly clicked on "update.bat" for forge and now the image browser has become a page saying "upload an image" and i have no idea how to fix it
<img width="1239" alt="chrome_VcbeK7EZ7K" src="https://github.com/user-attachments/assets/bf3805bf-6a32-457f-ab01-0fc54841104b">

**Comment by Vadim-Karpenko** [comment]
Same here.

**Comment by AlUlkesh** [comment]
Oh wow, that looks very broken. Let me download forge and see going on.

**Comment by AlUlkesh** [comment]
Well, it seems to be related to forge's switch to gradio 4 (as far as I know as the first webui). I suspect other extensions will have problems too...

Unfortunately the actual problem seems not to be easy to find, I'll have to put more time into that.

In the meantime, if you want, you can return to the pre-gradio-4 commit of forge like this:

`git checkout a9e0c38`

And later, you can return to the current version with:

`git checkout main`

Alternatively, since forge has annouced it will be more experimental and occasionally broken in the future, you might want to consider this alternative:

https://github.com/Panchovix/stable-diffusion-webui-reForge

**Comment by atmogenic** [comment]
> Well, it seems to be related to forge's switch to gradio 4 (as far as I know as the first webui). I suspect other extensions will have problems too...
> 
> Unfortunately the actual problem seems not to be easy to find, I'll have to put more time into that.
> 
> In the meantime, if you want, you can return to the pre-gradio-4 commit of forge like this:
> 
> `git checkout a9e0c38`
> 
> And later, you can return to the current version with:
> 
> `git checkout main`
> 
> Alternatively, since forge has annouced it will be more experimental and occasionally broken in the future, you might want to consider this alternative:
> 
> https://github.com/Panchovix/stable-diffusion-webui-reForge

thanks for the help unfortunately i'm not a techie at all with this stuff, i've got a1111 and forge which forge i went to In May this year. I want to check out reforge, but it has stuff to do with GIT and I do have git but have no idea where i meant to copy and paste that bunch of git stuff that is pasted on the reforge page.

**Comment by AlUlkesh** [comment]
@atmogenic 
Are you on Windows? If so, you can proceed like this to install reForge:

- Use Windows Explorer to navigate to the folder where you want to install into. For example `c:\ai`
- Then left click somewhere in the empty space on the address bar:

![image](https://github.com/user-attachments/assets/f0191ff7-29c0-417b-8b1d-4f4869f6a6d3)

- and type `cmd`
- You should now be in a terminal window and in the correct path. For a clean install do this then:
 
```
git clone https://github.com/Panchovix/stable-diffusion-webui-reForge
cd stable-diffusion-webui-reForge
webui-user.bat
```

Hope this helps.
