### ISSUE TITLE
While searching by exif keyword, some images only respond to the last line in prompt.

### ISSUE THREAD

**Issue by Burnil** [AlUlkesh/stable-diffusion-webui-images-browser#42]
When i tried searching for images i noticed that some images cannot be found by typing their keyword in exif search. After some investigation i found that the images can only be found by searching keywords from the last line in the prompt. What is interesting is that not all images with line breaks in the prompt have this problem. If i need to provide the faulty images for investigation then i can do so.

**Comment by AlUlkesh** [comment]
That actually makes sense. Newline is the delimiter between prompt, negative prompt and settings. If newlines can also be inside a prompt, that breaks the current parsing. Obviously I've never done that, so that didn't come up in testing.

I'll have to think about how to get around that, esp. since prompt and negative prompt are optional.

**Comment by AlUlkesh** [comment]
Should be fixed now. For more information see here: https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/discussions/44
