### ISSUE TITLE
Feature request: delete more than 1 page of images at a time

### ISSUE THREAD

**Issue by marcdacosta** [AlUlkesh/stable-diffusion-webui-images-browser#48]
I use Image Browser in combination with Deforum. My usecase is to delete the last few hundred images as I adjust prompts while building Deforum animations. Currently, the 'delete_next' function seems to be limited to the currently displayed page of images. It would be wonderful if the logic allowed deleting n number of images across subsequent pages.

**Comment by AlUlkesh** [comment]
@marcdacosta 
This implements this feature. Since I suspect there are some users that always enter 999 to delete to the end of the screen, I didn't want to make it a default...

So there's a checkbox now:

![image](https://user-images.githubusercontent.com/99896447/223263376-ecbffb31-433b-4274-8d46-22caba8b2503.png)
