### ISSUE TITLE
Feature request: Get Exif/PNG info or send to PNG Info

### ISSUE THREAD

**Issue by Aamir3d** [AlUlkesh/stable-diffusion-webui-images-browser#66]
Automatic1111 generated PNGs and JPG have PNG and Exif info within them, and Image Browser captures and displays this info easily.

However, I noticed that Image browser does not grab PNG info from InvokeAI or other PNGs.
A 'nice to have' feature would be
1. Get PNG / EXIF information from other applications 
2. If not, add "Send to PNG Info" button in the application (Next to "Send to extras") - the PNG info tab within the Automatic1111 UI is able to read any JPG/PNG information.

**Comment by AlUlkesh** [comment]
Can you upload a few example images?

**Comment by Aamir3d** [comment]
1. Example of no info
![image](https://user-images.githubusercontent.com/122131887/223211028-fcfbad07-46d1-4379-accf-9d7929bda4a1.png)
2. The same image in PNG Info shows the generation parameters (even though you can't send the parameters to Text2Img or Img2img, you can still copy paste it)
![image](https://user-images.githubusercontent.com/122131887/223211281-f5e26cd2-0cf7-4522-a48c-91118e20523b.png)
3. Good to have "Send to PNG Info"
![image](https://user-images.githubusercontent.com/122131887/223211616-e296ee09-72bd-4c36-9097-633dbd8ed993.png)

Of course, if Image Browser can pull the PNG info, this above button for is not necessary (but maybe Send to Text2Img/Img2Img buttons should work by sending the pulled information)

**Comment by AlUlkesh** [comment]
Can you upload some actual images? I need to see what is different about them.

**Comment by AlUlkesh** [comment]
Wait... do you mean just displaying that info? Or did you have using it in mind?

**Comment by Aamir3d** [comment]
> Wait... do you mean just displaying that info? Or did you have using it in mind?

If it displays the info in the "Generate Info" box, it's pretty good as it is (it will save a ton of time not having to search the folder for the image and drag it to PNG info).
Even better would be to send the info to Txt and Img2Img sections if possible for actioning.

**Comment by AlUlkesh** [comment]
Ok, here's the display part. I can't use the current box, that one is exclusive for parsed data, which can also be searched upon. Also the pnginfo-page has a much wider box. It would be very hard to read the info in the current box.
So I have put it on the bottom of the page,  with a gradio accordion, since most of the time it just doubles the information:

![image](https://user-images.githubusercontent.com/99896447/223390091-3761a1f3-656c-47c9-9846-a9ce16c2cc74.png)

**Comment by Aamir3d** [comment]
**... this request was yesterday and I'm already seeing this live.**
Thank you for spending of your time and skills to do this so fast.
Already started using the extension with the new feature, and every useful addition makes it that much more amazing to use.
Thanks again!

**Comment by AlUlkesh** [comment]
Thanks.
Well, I'm not really sure how I would integrate that. Without parsing you could only search the text as a whole. Which would include any negative prompts. Also it would be slow, since it's not cached.

I think this would need a conversion of the info to webui format, so it could be fully integrated.

**Comment by Aamir3d** [comment]
> Thanks. Well, I'm not really sure how I would integrate that. Without parsing you could only search the text as a whole. Which would include any negative prompts. Also it would be slow, since it's not cached.
> 
> I think this would need a conversion of the info to webui format, so it could be fully integrated.

Understood. I appreciate what you've done so far regardless!
Have a great day!

**Comment by AlUlkesh** [comment]
With the latest update, to see the Additional Generation Info, this box needs to be ticked in Settings:

![image](https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/assets/99896447/1a326929-8009-4334-8071-bbd4f3c810c7)

It's false by default, since I noticed it slows down certain parts of the browser, due to having to reread the info from the image.
