### ISSUE TITLE
Unable to sort or filter by Aesthetic Score on webp's

### ISSUE THREAD

**Issue by briancw** [AlUlkesh/stable-diffusion-webui-images-browser#73]
Webp files are correctly showing exif data in the browser, including score, but setting a minimum aesthetic score hides all webp images.

**Comment by AlUlkesh** [comment]
Currently only png and jpg are parsed for their information. I'll change that section, so that that data is read the same way webui's pnginfo does.

**Comment by AlUlkesh** [comment]
I was mistaken, that was already fixed with #30.

I'll try to find what is going wrong here.

**Comment by AlUlkesh** [comment]
This should have been fixed with https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/30, but as it turns out, that fix was only partial. I'll put a new fix in.

**Comment by AlUlkesh** [comment]
This should fix that. However, since there are already empty values in the database you'll have to do one additional step:

1. Update extension
2. Restart webui
3. Go to maintenance tab and press "Delete 0-entries from exif cache"
4. Once that is finished it should pick up the info from non-png/jpg files

**Comment by briancw** [comment]
Beautiful, seems to be working well now.
