### ISSUE TITLE
Support mp4 videos

### ISSUE THREAD

**Issue by krokosik** [AlUlkesh/stable-diffusion-webui-images-browser#87]
I love this extension and it's very useful when working with remote instances. However, we are using the Deforum extension for creating videos and it's not possible to access the outputs, only the individual frames. The Deforum extension itself allows to view the last output video right after generation. Are there any plans to support viewing or even just downloading videos? I can also try and submit a PR for that.

**Comment by AlUlkesh** [comment]
I hadn't planned video so far.

What are your ideas, how this should be implemented? A full seamless integration would have many detail problems I think.

So, simply a separate button to show the video, if pressed while positioned on a frame thumbnail?

**Comment by wkrasnicki** [comment]
I dug into the code after posting this and I agree that it would be difficult to integrate into this extension. Especially due to reliance on the `Gallery` component from gradio, which does not support videos at all.
To make thumbnails a reality we would probably have to pass a callback instead of the filename and generate a thumbnail with PIL or something. I don't there is a way to embed any actual functionality in there.
Other solutions that come to mind are even more messy, the best approach would be to probably create a separate tab or even extension based on your file traversal functionality.

**Comment by AlUlkesh** [comment]
See #241
